name: Session4 Job1 Input

on:
  workflow_dispatch:
    inputs:
      testcase:
        description: 'Test case name (khop voi tieu de test trong file .spec.ts)'
        required: true
        type: string

jobs:
  dispatch-job2:
    runs-on: self-hosted
    permissions:
      actions: write
    steps:
      - name: trigger session4-job2-execute as an independent run
        uses: actions/github-script@v7
        env:
          TESTCASE: ${{ inputs.testcase }}
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'session4-job2-execute.yml',
              ref: context.ref,
              inputs: {
                testcase: process.env.TESTCASE
              }
            })
